model: kvadra
wandb_project: dped_300k
dped_dir: dped/
vgg_dir: vgg_pretrained/imagenet-vgg-verydeep-19.mat

batch_size: 50
train_size: 30000
learning_rate: 2e-4
num_train_iters: 20000
eval_step: 1000
gpu_number: 0

w_content: 10
w_color: 2
w_texture: 4
w_tv: 2000

log_dir: epoch_3
result_dir: results

